---

hostname: leaf02
interfaces:
  - name: lo
    auto: true
    ipv4: 10.0.0.12/32
    ipv6_ula: fc00::10:0:0:12/128
    ipv6_lla: fe80::12
  - name: eth0
    auto: true
    ipv4: 192.168.100.12/24
  - name: swp1
    auto: true
    ipv4: 10.10.12.12/24
    ipv6_ula: fc00::10:10:12:12/64
    ipv6_lla: fe80::12
  - name: swp2
    auto: true
    ipv4: 10.20.12.12/24
    ipv6_ula: fc00::10:20:12:12/64
    ipv6_lla: fe80::12
  - name: swp3
    auto: true
    ipv4: 10.0.12.1/24

routing:
  bgp:
    asn: 65012
    router_id: 10.0.0.12
    as_path_relax: true
    neighbors:
      - peer_ip: 10.10.12.10
        peer_asn: 65001
        ipv4: true
        evpn: false
      - peer_ip: 10.20.12.20
        peer_asn: 65001
        ipv4: true
        evpn: false
      - peer_ip: 10.0.0.11
        peer_asn: 65011
        ipv4: false
        evpn: true
        update_source: 10.0.0.12
      - peer_ip: 10.0.0.13
        peer_asn: 65013
        ipv4: false
        evpn: true
        update_source: 10.0.0.12
      - peer_ip: 10.0.0.14
        peer_asn: 65014
        ipv4: false
        evpn: true
        update_source: 10.0.0.12
    networks: 
      - 10.0.0.12/32
