---

hostname: leaf04
interfaces:
  - name: lo
    auto: true
    ipv4: 10.0.0.14/32
    ipv6_ula: fc00::10:0:0:14/128
    ipv6_lla: fe80::14
  - name: eth0
    auto: true
    ipv4: 192.168.100.14/24
  - name: swp1
    auto: true
    ipv4: 10.10.14.14/24
    ipv6_ula: fc00::10:10:14:14/64
    ipv6_lla: fe80::14
  - name: swp2
    auto: true
    ipv4: 10.20.14.14/24
    ipv6_ula: fc00::10:20:14:14/64
    ipv6_lla: fe80::14

routing:
  bgp:
    asn: 65014
    router_id: 10.0.0.14
    as_path_relax: true
    neighbors:
      - peer_ip: 10.10.14.10
        peer_asn: 65001
        ipv4: true
        evpn: false
      - peer_ip: 10.20.14.20
        peer_asn: 65001
        ipv4: true
        evpn: false
    networks: 
      - 10.0.0.14/32
