---

hostname: spine02
interfaces:
  - name: lo
    auto: true
    ipv4: 10.0.0.20/32
    ipv6_ula: fc00::10:0:0:20/128
    ipv6_lla: fe80::20
  - name: eth0
    auto: true
    ipv4: 192.168.100.20/24
  - name: swp1
    auto: true
    ipv4: 10.20.11.20/24
    ipv6_ula: fc00::10:20:11:20/64
    ipv6_lla: fe80::20
  - name: swp2
    auto: true
    ipv4: 10.20.12.20/24
    ipv6_ula: fc00::10:20:12:20/64
    ipv6_lla: fe80::20
  - name: swp3
    auto: true
    ipv4: 10.20.13.20/24
    ipv6_ula: fc00::10:20:13:20/64
    ipv6_lla: fe80::20
  - name: swp4
    auto: true
    ipv4: 10.20.14.20/24
    ipv6_ula: fc00::10:20:14:20/64
    ipv6_lla: fe80::20

routing:
  bgp:
    asn: 65001
    router_id: 10.0.0.20
    as_path_relax: true
    neighbors:
      - peer_ip: 10.20.11.11
        peer_asn: 65011
        ipv4: true
        evpn: false
      - peer_ip: 10.20.12.12
        peer_asn: 65012
        ipv4: true
        evpn: false
      - peer_ip: 10.20.13.13
        peer_asn: 65013
        ipv4: true
        evpn: false
      - peer_ip: 10.20.14.14
        peer_asn: 65014
        ipv4: true
        evpn: false
    networks:
      - 10.0.0.20/32
