---

- name: CONFIGURING SPINES
  hosts: cumulus-spines
  gather_facts: false

  tasks:

    - name: IMPORTING HOST SPECIFIC DATA
      include_vars:
        file: "{{ inventory_hostname }}.yml"

    - name: CONFIGURING INTERFACES
      blockinfile:
        block: "{{ lookup ('template', 'iface.j2') }}"
        path: /etc/network/interfaces
      become: true

    - name: RELOADING INTERFACE CONFIGURATION
      shell: ifreload -a
      become: true


- name: CONFIGURING LEAFS
  hosts: cumulus-leafs
  gather_facts: false

  tasks:

    - name: IMPORTING HOST SPECIFIC DATA
      include_vars:
        file: "{{ inventory_hostname }}.yml"

    - name: CONFIGURING INTERFACES
      blockinfile:
        block: "{{ lookup ('template', 'iface.j2') }}"
        path: /etc/network/interfaces
      become: true

    - name: RELOADING INTERFACE CONFIGURATION
      shell: ifreload -a
      become: true