- include vars: 
    file: "{{ inventory_hostname }}.yml"
    
- name: CONFIGURING BGP
  blockinfile: 
    block: "{{ lookup ('template, 'bgpd.j2') }}"
    path: /etc/frr/bgpd.conf
  become: true

- name:  RELOADING FRR 
  service:
    name: frr
    state: restarted
